{% set version = "0.4.12" %}

package:
  name: selectolax
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/selectolax/selectolax-{{ version }}.tar.gz
  sha256: 078f6bfac14439395d57eaf46887ec78362e19178ca90bc69da7420253a3e9d5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - cython ==3.0.11
    - python

test:
  imports:
    - selectolax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rushter/selectolax
  summary: Fast HTML5 parser with CSS selectors.
  license: Apache-2.0 AND LGPL-2.1-only AND MIT
  license_file:
    - LICENSE
    - lexbor/LICENSE
    - lexbor/NOTICE
    - modest/LICENSE
  doc_url: https://selectolax.readthedocs.io

extra:
  recipe-maintainers:
    - rxm7706
    - soapy1
